{\rtf1\ansi\ansicpg1252\cocoartf2758
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww14740\viewh9860\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs28 \cf0 ---\
- name: Provision EC2 instance\
  hosts: localhost\
  vars:\
      region:   eu-east-2\
      ami:      \expnd0\expndtw0\kerning0
ami-0cd3c7f72edd5b06d\kerning1\expnd0\expndtw0 \
      set_dns:  False\
      instance: t1.micro\
  connection: local\
  gather_facts: false\
  tasks:\
    - name: Launch instance\
      ec2:\
        keypair=Hareesh\
        instance_type=\{\{ t2.micro \}\}\
        image=\{\{ \expnd0\expndtw0\kerning0
ami-0cd3c7f72edd5b06d\kerning1\expnd0\expndtw0  \}\}\
        region=\{\{ us-east-2 \}\}\
        wait=yes\
      register: ec2\
\
    - name: Add new instance to host group\
      local_action: add_host hostname=\{\{ \expnd0\expndtw0\kerning0
ec2-3-136-112-61.us-east-2.compute.amazonaws.com \kerning1\expnd0\expndtw0 \}\}\
                    groupname=launched\
      with_items: ec2.instances\
\
    - name: Ensure DNS entry exists\
      route53: command=create overwrite=yes\
               record=ci.\{\{ ZONENAME \}\} type=A zone=\{\{ ZONENAME \}\}\
               value=\{\{ \expnd0\expndtw0\kerning0
3.136.112.61\kerning1\expnd0\expndtw0  \}\}\
      with_items: ec2.instances\
      when: set_dns\
\
    - name: Wait for SSH to come up\
      local_action: wait_for host=\{\{ \expnd0\expndtw0\kerning0
ip-172-31-18-137.us-east-2.compute.internal\kerning1\expnd0\expndtw0  \}\}\
                    port=22 delay=60 timeout=320 state=started\
      with_items: ec2.instances\
\
- include: main.yaml}